<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 taxi.glb
-->

<script>
	import { T } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	let {
		fallback = undefined,
		error = undefined,
		children = undefined,
		ref = $bindable(),
		...props
	} = $props()

	const gltf = useGltf('/3d-models/taxi.glb')
</script>

<T.Group bind:ref dispose={false} rotation.y={Math.PI} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			castShadow
			geometry={gltf.nodes.body.geometry}
			material={gltf.materials.colormap}
			position={[0, 0.15, -0.03]}
		/>
		<T.Mesh
			castShadow
			geometry={gltf.nodes['wheel-front-right'].geometry}
			material={gltf.materials.colormap}
			position={[-0.3, 0.3, 0.76]}
		/>
		<T.Mesh
			castShadow
			geometry={gltf.nodes['wheel-front-left'].geometry}
			material={gltf.materials.colormap}
			position={[0.3, 0.3, 0.76]}
		/>
		<T.Mesh
			castShadow
			geometry={gltf.nodes['wheel-back-left'].geometry}
			material={gltf.materials.colormap}
			position={[0.3, 0.3, -0.76]}
		/>
		<T.Mesh
			castShadow
			geometry={gltf.nodes['wheel-back-right'].geometry}
			material={gltf.materials.colormap}
			position={[-0.3, 0.3, -0.76]}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
